export const candidateSelect = [
  'id',
  'organization_id',
  'full_name',
  'cpf',
  'cpf_normalized',
  'rg',
  'identity_document_type',
  'birth_date',
  'phone',
  'email',
  'postal_code',
  'street',
  'address_number',
  'address_complement',
  'neighborhood',
  'city',
  'state',
  'cnh_number',
  'cnh_category',
  'cnh_expires_at',
  'notes',
  'created_by',
  'created_at',
  'updated_at',
].join(', ');

export const candidateFields = [
  'full_name',
  'cpf',
  'rg',
  'identity_document_type',
  'birth_date',
  'phone',
  'email',
  'postal_code',
  'street',
  'address_number',
  'address_complement',
  'neighborhood',
  'city',
  'state',
  'cnh_number',
  'cnh_category',
  'cnh_expires_at',
  'notes',
] as const;

export type CandidateField = (typeof candidateFields)[number];
